worlds:
  # Add a section for each world using Earthcraft as a generator
  "world":
    # Latitude/Longitude projection
    # Currently only EquirectangularProjection is supported
    mapProjection:
      # Equirectangular Projection
      # Maps lat/lon linearly to x/z. Causes severe distortion at most
      # latitudes.
      EquirectangularProjection:
        # location of the block (0,0)
        # lat/lon are in degrees
        origin: [0,0]
        # Scale of the world
        # lat/lon are in degrees/block
        scale: [0.001, 0.001]
    # Elevation scale
    # Currently only LinearElevationProjection is supported
    elevationProjection:
      # Linear elevation scale
      LinearElevationProjection:
        scale: 10 # meters/block
        #elev: -40.0 # meters; Elevation of the bottom of bedrock
        seaLevel: 64 # blocks; height of first dry block
    # location of the spawn point, in degrees
    spawn: [ 32.73, -117.26 ]
    # data sources
    sources:
      # source for elevation data
      elevation:
        ## A cache to wrap another provider and reduce overhead
        ## Recommended for online sources to reduce server load
        ## Uses nearest neighbor interpolation
        #InterpolatingElevationCache:
        #  # Primary elevation source
        #  provider:
        #    # Get elevation data from MapQuest's Open Elevation API
        #    OpenElevationConnector: {}
        #  # Spacing of the cache grid
        #  gridunit: degrees #or blocks
        #  grid: [ .004, .004 ]
        #  #Optionally, also specify grid origin (not needed) as origin.lat/lon
        #  origin: [ 0, 0 ]

        ## A fully offline provider, for testing projections
        ## Creates elevations within a rectangle increasing to the northeast.
        ## The south of the box has uniform low elevation, and areas outside the box
        ## have random elevation.
        #TestElevationProvider:
        #  # coordinates of the well-defined box
        #  south: 32.73
        #  north: 32.80 #84 blocks
        #  west: -117.26
        #  east: -117.20 # 72 blocks
        #  # elevation scale
        #  min: 0
        #  max: 64

        # Fetch SMRT elevation data
        InterpolatedCoverageElevationProvider:
          provider:
            SRTMPlusElevationProvider: {}
              cache: /Users/blivens/dev/minecraft/srtm
              # tile the map over and over, or just truncate it at the dateline
              # and show water?
              wrap: Yes

    # Should we spawn water? (Useful when debugging bathymetry)
    spawnOcean: Yes

# vi: ts=2 sw=2 et
