worlds:
  world:
    projection:
      # Currently only EquirectangularProjection is supported
      type: EquirectangularProjection
      parameters:
        origin:
          # location of the block (0,0,0)
          # lat/lon are in degrees, elev in meters
          lat: 32.73
          lon: -117.26
          elev: -40.0
        scale:
          # Scale of the world
          # lat/lon are in degrees/block, elev in m/block
          lat: .001
          lon: .001
          elev: 1
    spawn:
      # location of the spawn point, in degrees
      lat: 32.73
      lon: -117.26
    sources: # data sources
      elevation: # source for elevation data
        # A cache to wrap another provider and reduce overhead
        # Recommended for online sources to reduce server load
        # Recommended for low-resolution sources to smooth the landscape
        type: InterpolatingElevationCache
        parameters:
          provider:
            # Get elevation data from MapQuest's Open Elevation API
            #type: OpenElevationConnector
            #parameters: {}
            
            # A fully offline provider, for testing projections
            # Creates elevations within a rectangle increasing to the northeast.
            # The south of the box has uniform low elevation, and areas outside the box
            # have random elevation.
            type: TestElevationProvider
            parameters:
              # coordinates of the well-defined box
              south: 32.73
              north: 32.80 #84 blocks
              west: -117.26
              east: -117.20 # 72 blocks
              # elevation scale
              min-elev: 0
              max-elev: 64 
              
            # Fetch SMRT elevation data
            #type: SRTMPlusElevationProvider
            #parameters:
            #  cache-dir: /Users/blivens/dev/minecraft/srtm
              
          scale:
            # Spacing of the cache grid, in degrees
            # locations between points will be linearly interpolated
            lat: .004
            lon: .004
          #Optionally, also specify grid origin (not needed) as origin.lat/lon
    # tile the map over and over, or just truncate it at the dateline and show water?
    wrap: Yes