name: "${project.name}"
author: "Spencer Bliven"
version: "${project.version}"
main: us.bliven.bukkit.earthcraft.EarthcraftPlugin
website: "${project.url}"
load: STARTUP
description: "A world generator using real-world terrain data"
softdepends: [BukkitPopulators,SkylandsPlus]
commands:
  earth:
    description: General Earthcraft command
    usage: /<command> cmd [options]
    aliases: [ec]
  earthpos:
    description: Get your world position as latitude,longitude
    usage: /<command> [player]
    permission: earthcraft.info
    permission-message: You don't have permission <permission>
    aliases: [ecpos]
  earthtp:
    description: Teleport to the specified latitude and longitude
    usage: |
      /<command> [player] lat lon [elev]
      /<command> [player] landmark
    permission: earthcraft.tp
    permission-message: You don't have permission <permission>
    aliases: [ectp]
  earthelev:
    description: Get the elevation at a particular coordinate
    usage: |
      /<command> [lat lon]
      /<command> [landmark]
    permission: earthcraft.info
    permission-message: You don't have permission <permission>
    aliases: [ecelev]
  earthclimate:
    description: Print information about the climate at a location
    usage: |
      /<command> [lat lon]
      /<command> [landmark]
    permission: earthcraft.info
    permission-message: You don't have permission <permission>
    aliases: [ecclimate,ecinfo,earthinfo]
permissions:
  earthcraft.*:
    description: All Earthcraft commands
    children:
      earthcraft.info: true
      earthcraft.tp: true
      earthcraft.tp.others: true
  earthcraft.tp:
    description: Allow teleportation
    default: op
  earthcraft.tp.others:
    description: Allow teleportation of other people
    default: op
    children:
      earthcraft.tp: true
  earthcraft.info:
    description: Permit commands which give information about world locations
    default: true
