name: "${project.name}"
author: "Spencer Bliven"
version: "${project.version}"
main: us.bliven.bukkit.earthcraft.EarthcraftPlugin
website: "${project.url}"
load: STARTUP
description: "A world generator using real-world terrain data"
softdepends: [BukkitPopulators,SkylandsPlus]
commands:
  earth:
    description: General Earthcraft command
    usage: /<command> cmd [options]
    aliases: [ec]
  earthpos:
    description: Get your world position as latitude,longitude
    usage: /<command> [player]
    permission: earthcraft.pos
    permission-message: You don't have permission <permission>
    aliases: [ecpos]
  earthtp:
    description: Teleport to the specified latitude and longitude
    usage: |
      /<command> [player] lat lon [elev]
      /<command> [player] landmark
    permission: earthcraft.tp
    permission-message: You don't have permission <permission>
    aliases: [ectp]
  earthelev:
    description: Get the elevation at a particular coordinate
    usage: /<command> [lat lon]
    permission: earthcraft.pos
    permission-message: You don't have permission <permission>
    aliases: [ecelev]
permissions:
  earthcraft.*:
    description: All Earthcraft commands
    children:
      earthcraft.pos: true
      earthcraft.tp: true
      earthcraft.tp.others: true
  earthcraft.tp:
    description: Allows you to teleport
    default: op
  earthcraft.tp.others:
    description: Allows you to teleport other people
    default: op
    children:
      earthcraft.tp: true
  earthcraft.pos:
    description: Allows you to see your latitude, longitude, and elevation
    default: true
